version: "3.6"

services:
  rest:
    container_name: sword_rest
    build: .
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_URL: amqp://sword:sword@rabbitmq:5672/dev
      RABBITMQ_EXCHANGE: sword
      RABBITMQ_ROUTING_KEY: tasks
      RABBITMQ_QUEUE: tasks
      DB_NAME: sword
      DB_USER: sword
      DB_PASSWORD: sword
      DB_HOST: mysql
      DB_PORT: 3306

  consumer:
    container_name: sword_consumer
    build: .
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://sword:sword@rabbitmq:5672/dev
      RABBITMQ_EXCHANGE: sword
      RABBITMQ_ROUTING_KEY: tasks
      RABBITMQ_QUEUE: tasks
      DB_NAME: sword
      DB_USER: sword
      DB_PASSWORD: sword
      DB_HOST: mysql
      DB_PORT: 3306
      PYTHONUNBUFFERED: 0
    command: [ "python", "-u", "consume.py" ]

  mysql:
    container_name: sword_mysql
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sword
      MYSQL_USER: sword
      MYSQL_PASSWORD: sword
      MYSQL_DATABASE: sword
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - sword_mysql_volume:/var/lib/mysql

  rabbitmq:
    container_name: sword_rabbitmq
    image: 'rabbitmq:3-management'
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_PASS: 'sword'
      RABBITMQ_DEFAULT_USER: 'sword'
      RABBITMQ_DEFAULT_VHOST: 'dev'
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  sword_mysql_volume:
